# Generated by Django 3.2.12 on 2022-02-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('amount', models.CharField(max_length=20)),
                ('payment_id', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
